FROM ruby:3.2.2

# 必要なパッケージのインストール
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    npm \
    yarn \
    git \
    vim

# 作業ディレクトリの設定
WORKDIR /rails

# ポート3000を公開
EXPOSE 3000